### PR TITLE
Fixed reference issue for actionInfo settings and actions

### PR DESCRIPTION
**Pull request by Inaamhusain**
Fixed following,
1) Actioninfo settings not changing reference due to which action settings form not loading.
2) Clear cache onload action.
3) Setting form edit action URL update.
4) Removed form-action attr from edit action page template.

### CODE REVIEW

**Comment by Inaamhusain** [comment]
@randallknutson Can you please check this too.

**Comment by Inaamhusain** [comment]
@randallknutson I have made some modifications related to actions page. and it perfectly works well with latest formio version. can you please check and update accordingly.

**Comment by Inaamhusain** [comment]
@randallknutson @travist Can you please review.

**Comment by Inaamhusain** [comment]
@randallknutson @travist can you please check changes that I have made to support formiojs v4.
I need these changes to be in place before proceeding to version update.

**Comment by travist** [comment]
We will take a look during out next build processes that change our legacy renderer.

**Pull request closed without merging**
